version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assignment_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"