spring.application.name=assignmentAndazKumar

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/assignment_db
spring.datasource.username=user
spring.datasource.password=password
# 'update' automatically creates your tables based on the JPA Entities we mapped
spring.jpa.hibernate.ddl-auto=update
# Helpful to see the SQL Spring generates in your terminal
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Enable Scheduling (For Phase 3 CRON Sweeper)
spring.task.scheduling.pool.size=2